### PR TITLE
Parse SMILES strings

### PR DESCRIPTION
**Pull request by kuelumbus**
Really cool project and very helpful. This PR adds SMILES string support using RDKit. 

For example, styrene
```bash
asciimol C=Cc1ccccc1
```

### CODE REVIEW

**Comment by dewberryants** [comment]
I've also been thinking about how to easily handle more file formats and I think it would be more practical to use something dedicated to file formats specifically, such as openbabel (might be too cumbersome) or IOData (https://github.com/theochem/iodata , does not handle SMILES sadly), so that we can hand off the I/O and instantly get all supported formats. Otherwise, very nice idea and you are right, it's really an important missing feature.

I'm currently on vacation so I'll look into it as soon as I'm back. :+1:

**Comment by dewberryants** [comment]
PS: Maybe moving to ASE could be a way to go, and then simply use ASEs own atoms objects internally. ASE can read a lot of formats and can use pubchem integration to generate molecules from SMILES.

**Comment by dewberryants** [comment]
I've implemented my idea in #9. What do you think?
Its kind of weird that ASE's SMILES resolution depends on internet access.

However, I'm not sure I if I want RDKit as a hard dependency.

**Comment by kuelumbus** [comment]
ASE searches in PubChem for conformers. I assume this fails if the SMILES/ molecule is unknown (has not been synthesized before). That's quite restricting for a tool that aims to display structures. 



> However, I'm not sure I if I want RDKit as a hard dependency.

Any reason for this?

**Comment by dewberryants** [comment]
> Any reason for this?

I wanted to sort of stick with the simplicity of having only numpy as a hard dependency. Most linux distributions come with numpy, but probably not with ASE or RDKit. But maybe that's unjustified, as pip can just take care of these for you. I'll merge this and fix the build, I can always decide to make it an optional dependency again. :)

**Comment by kuelumbus** [comment]
> > Any reason for this?
> 
> I wanted to sort of stick with the simplicity of having only numpy as a hard dependency. Most linux distributions come with numpy, but probably not with ASE or RDKit. But maybe that's unjustified, as pip can just take care of these for you. I'll merge this and fix the build, I can always decide to make it an optional dependency again. :)

Regarding your concern: 
I understand. ASE is (as far as I know) a pure Python package (no C or Fortran code). It should be available for all Linux distros and work out of the box, without compilation or platform wheels necessary. RDKit is different and requires platform wheels to work on different distros and architectures. However, the most commonly used wheels are available at PyPi (I am the developer who's taking care of the pypi RDKit wheels).

**Pull request merged**
